---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres:9.6.13
    spec:
      containers:
        - name: master
          image: postgres
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 1
              memory: 1000Mi
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "${POSTGRES_PASSWORD}"
