version: 2
jobs:
  build:
    docker:
      - image: erulabs/circleci-builder:11
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Installing
          command: yarn --no-progress --no-emoji --prefer-offline

      - run:
          name: Linting
          command: ./node_modules/.bin/eslint .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
